remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: MarTech Landscape
description: The collection of MarTech platforms presented to you by MarTech Association
logo: assets/img/logo.jpg